name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${author}
depend: []
api-version: 1.20

main: ${mainClass}
commands:
   weatherman:
      aliases: [wm, wman]
      description: Main WeatherMan command
      usage: |
           /wm help
   wth:
      aliases: [localweather, lweather, lwth]
      description: Local weather control command
      usage: |
           /wth <player|region|biome|world> [{name} <rain|clear|remove>]
   wtm:
      aliases: [ltime, localtime, ltm]
      description: Local time control command
      usage: |
           /wtm <player|region|biome|world> [{name} <DAY|NIGHT|HH:SS|remove>]
   mytime:
      aliases: [mtime, mytm]
      description: Configure your own personal time
      usage: |
           /mytime <DAY|NIGHT|HH:SS|remove>]
   myweather:
      aliases: [mweather, mwth, mywth]
      description: Configure your own personal time
      usage: |

permissions:
   weatherman.basic:
      description: Basic permissions
      default: op
   weatherman.mytime:
      description: Allows to set player own time
      default: op
   weatherman.myweather:
      description: Allows to set player weather time
      default: op
   weatherman.wandbiome:
      description: Allows to use wand commands
      default: op
   weatherman.repopulate:
      description: Allows to repopulation commands
      default: op
   weatherman.cmdbiome:
      description: Allows to use set and replace biome commands
      default: op
   weatherman.time:
      description: Allows to configure local time
      default: op
   weatherman.weather:
      description: Allows to configure local weather
      default: op